### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by garymm**
Thanks a lot for writing and publishing this document. I found it very helpful. I hope you don't find it impertinent of me to suggest some minor improvements.

The interesting things are all in the second commit.

### CODE REVIEW

**Comment by parrt** [comment]
Hi @garymm. I'll have a look next time I take a pass at this article. thank you.

**Comment by garymm** [comment]
Hi @parrt, do you have time to review this?

**Comment by parrt** [comment]
Hi.  those changes do look very interesting but I am so overwhelmed at the moment I can't really look at it. sorry!

**Comment by parrt** [comment]
hi! Thanks very much for submitting. Some of the changes are because of white space which makes it hard to see what the real changes are. Could you tweak it so that only the real changes appear in my diff? Thanks!

**Comment by garymm** [comment]
@parrt the first commit has all the whitespace diffs. You can see the diffs excluding that commit here:
https://github.com/parrt/bookish/pull/5/files/a125a4685f64208b7257e5b2a29a2e3bf859005f..1f68ca3deb02a94b9c19b6ec4308288615ec27fb

**Comment by garymm** [comment]
Basically everything is in the second commit here, and its commit message explains the rationale:
https://github.com/parrt/bookish/pull/5/commits/caae2aa72c8e5837df3d5606ad15ca33813fca08

**Comment by parrt** [comment]
Ooops. we have a problem. My bookish tool doesn't process this much older doc anymore. I'd have to modify the https://github.com/parrt/website-explained.ai/blob/master/matrix-calculus/index.html file. Hmm...sorry about that.  It's been 4+ years.

**Comment by garymm** [comment]
Well not sure how much trouble it is, but could you check out and build an older version of bookish?
If not, then I guess just close this PR.

**Comment by parrt** [comment]
I thought about upgrading but I think I will just incorporate these changes after I check them and then manually update the website HTML. There are very few updates these days so it's the simplest solution. Checking the commit with the fixes now...

**Comment by parrt** [comment]
Actually we have a problem... Those are changes to the equation so I really do need to re-run the tool. damn. ok, let me spend a few minutes to see how bad off we are in terms of upgrading...

**Comment by parrt** [comment]
ok, i spent ~3 hours updating to work with latest bookish.  File is now index.xml.  I did all your your changes except for moving summations. Couldn't decipher my own latex / math enough to verify quickly so I left those alone. sorry!  thanks for fixes.  Can you check here? https://explained.ai/matrix-calculus/index.html

**Comment by garymm** [comment]
Thanks so much for maintaining this great resource!
If you ever have the energy, I'm pretty confident moving the summations is the right thing to do, for the reasons explained in the commit message of https://github.com/parrt/bookish/commit/caae2aa72c8e5837df3d5606ad15ca33813fca08

**Comment by parrt** [comment]
It would be easier for me if you made another Pull request that changed just those summations now in the new index file

**Pull request closed without merging**
